### ISSUE TITLE
Reminder tag missing Button

### ISSUE THREAD

**Issue by Konrni** [Blue-Reaper/Proxer-Essentials#104]
**System**
 - OS: Win 10
 - Browser: chrome
 - Version: Version 81.0.4044.138 (Offizieller Build) (64-Bit)
 - Userscript-Manager: Tampermonkey
 - Verison of Essentials: 6.3

**Describe the bug**
In "Lesezeichen" the Button "Nur verfügbare anzeigen" is only once visible.
The 2. pic shows the <p> which isn't moved out the <div>

**To Reproduce**
1. Go to 'https://proxer.me/ucp?s=reminder'

**Expected behavior**
2 visible Buttons "Nur verfügbare anzeigen"

**Screenshots**
![image](https://user-images.githubusercontent.com/39877017/82590992-ebb70680-9b9e-11ea-8efe-c716c2ed596f.png)
![image](https://user-images.githubusercontent.com/39877017/82591420-9af3dd80-9b9f-11ea-80ae-8491acfaccf9.png)

**Comment by Blue-Reaper** [comment]
Hey @Konrni,
I appreciate that you use the script and took your time to write this report.
Sorry for my late response and I hope you still enjoy it.

The reason is this:`$('.inner').hide();` -> to hide the original table
the div.inner also contains both "nur verfügbare anzeigen" buttons, the one at the end of the page is shown, because I moved it to the #main element:
`function showGridBookmarks(){
[...]
    $('#main').append($('.inner p:first-child'));
[...]
}`

I felt that one button was enough and I didn't want to "ruin" the desigen, because the search bar isn't very pretty.
Also if you minmise the open List, by clicking on the "headline" (red in the screenshot) you can see the lower button without scrolling:
![grafik](https://user-images.githubusercontent.com/46467587/100490505-1e2c5800-311c-11eb-909a-3ae748b51ea9.png)

Do you really miss the upper button and don't want to make the one extra click to get to the button or did you just report it, because you were used to have two buttons?

If it's the former I could look into it, if I can add it again, but if you just reportet it because you thought it was a mistake and wantet to help, then I won't add it of course. ;)

Best regards
Blue

This is the relevant file: https://github.com/Blue-Reaper/Proxer-Essentials/blob/master/src/modules/PictureTile.ts

**Comment by Konrni** [comment]
Hey Blue, 
i have to disappoint you, i stopped using your great script about a week after my post.
For my use of proxer it is a deal breaker to always scroll down and press "show only available". I do miss the preview picture, as this was the only feature i was using but mouse over with arrows works fine.

I doubt i'm the main audience for a total conversion mo as i like the default style. 
I will close this case but still wanted to tell you .

**Comment by Blue-Reaper** [comment]
Hey @Konrni,
in version 6.3.2 I did add the button "show only available" on top of the list:
![grafik](https://user-images.githubusercontent.com/46467587/104446761-3573b780-559b-11eb-8186-2670217e72e2.png)

So check it out and tell me what you think.
