### ISSUE TITLE
Theater Mode fehlerhaft

### ISSUE THREAD

**Issue by KamikazeSFA** [Blue-Reaper/Proxer-Essentials#114]
**System**
 - OS: WIN10
 - Browser: Chrome
 - Version: -
 - Userscript-Manager: Tampermonkey
 - Verison of Essentials: -

**Describe the bug**
Video Player wird nicht auf den ganzen Bildschirm gestreckt

**To Reproduce**
1. Anime starten
2. Theatermodus aktivieren
3. Error tritt auf

**Screenshots**
Screenshot mit aktivem Theater Modus: https://puu.sh/H29vZ/483ecc131b.png

**Comment by Blue-Reaper** [comment]
Hey @KamikazeSFA ,

I'm happy that you still use my script, you are one of the "1st hour" users.

which version of the script do you use?
You can see it in the menu "Essentials":
![grafik](https://user-images.githubusercontent.com/46467587/103628997-0b3d4c80-4f40-11eb-99c5-6c586f316a9c.png)

Is this a new bug (only on proxer.net or did it exist on proxer.me?
I'm asking because on proxer.net (which is only temporary because proxer had so many errors) I know that for example the Design doesn't really work. But I won't fix it, I will first wait till proxer runs on proxer.me. I think then the Design will also work without errors.

Greetings
blue
